### PR TITLE
Change gradient phase to be a range of -1f up to 1f

### LINKED ISSUE #35: [Bug] ArrayIndexOutOfBoundsException with multi-color gradients
Certain character lengths cause an exception when trying to apply a multi-color gradient. This issue is present in the latest master branch/sonatype.

This can be seen in the unit tests by modifying the input string of MiniMessageParserTest.testGradientMultiColor() from
```<yellow>Woo: <gradient:red:blue:green:yellow:red>||||||||||||||||||||||||||||||||||||||||||||||||||||||</gradient>!``` to
```<yellow>Woo: <gradient:red:blue:green:yellow:red>|||||||||||||||||||||||||||||||||||</gradient>!```
which will result in a test failure not due to the output not matching expected, but with [this stacktrace](https://paste.gg/p/anonymous/318bfdefff344daab3db7884d7fae526)

This is due to the sector length for sub-gradients having 1 subtracted from them. This causes all the sub gradients to have been completed before the end of the string to be colored by the gradient, causing ``if (factorStep * index > 1.1)`` to evaluate true one extra time.

This can be fixed by removing the subtraction of 1 and changing ``if (factorStep * index > 1.1)`` to ``if (factorStep * index > 1)``. This breaks all the gradient-related unit tests but visually looks fine to me in game. I have incorporated these changes in my PR #34 as they were necessary to get smooth gradient animations.

### LINKED ISSUE #48: Gradient shows black when only have one character
When using gradient with one character it shows black color. It should grab first or last color i think.

Example tag: `<gradient:#ad5389:#3c1053>Y</gradient>`

Expected: 
image
Result: 
image

It also black with obfuscated: 
image

`<gradient:#ad5389:#3c1053>Y<obfuscated>xyz</obfuscated></gradient>`

### PR DESCRIPTION
**Pull request by jmanpenilla**
- Change gradient phase to be a float with a range of -1 up to 1
  - This allows for easily looping a gradient by sending the phase -1 up to 1 repeating, [example](https://streamable.com/ggcpcp)
- Fix bug [where](https://github.com/KyoriPowered/adventure-text-minimessage/compare/master...jmanpenilla:master#diff-db6a68b30d299891610c004a019463d2R71) >2 color gradients were not smooth
- Fixed an Exception when certain character lengths were used with certain color amount gradients (closes #35)
  - From my testing this issue was present before I made any changes, so it must have been introduced and not noticed when MiniDigger was adding multi-color gradients
  - This also fixes #48 

Gradients with more than two colors that are not repeating (ie not r,g,r,g,r or b,y,b, something like: b,r,y) do not work well with phase. This is not a new issue to this PR though, it is a flaw with the way the multi-color gradients work.

### CODE REVIEW

File: src/main/java/net/kyori/adventure/text/minimessage/fancy/Gradient.java [hunk 1]
```diff
@@ -26,28 +26,41 @@
...
+
 public class Gradient implements Fancy {
 
   private int index = 0;
   private int colorIndex = 0;
 
   private float factorStep = 0;
-  private final TextColor[] colors;
-  private final int phase;
+  private TextColor[] colors;
```
Comment (kashike) [inline src/main/java/net/kyori/adventure/text/minimessage/fancy/Gradient.java:39]:
```suggestion
  private final TextColor[] colors;
```

File: src/main/java/net/kyori/adventure/text/minimessage/fancy/Gradient.java [hunk 2]
```diff
@@ -26,28 +26,41 @@
...
   public void init(int size) {
-    size = size / (colors.length - 1);
-    this.factorStep = (float) (1. / (size + this.index - 1));
+    final int sectorLength = size / (this.colors.length - 1);
+    this.factorStep = 1.0f / (sectorLength + this.index - 1);
+    if (this.phase < 0) {
+      this.negativePhase = true;
+      final List<TextColor> l = Arrays.asList(this.colors);
+      Collections.reverse(l);
+      this.colors = l.toArray(new TextColor[0]);
```
Comment (kashike) [inline src/main/java/net/kyori/adventure/text/minimessage/fancy/Gradient.java:60]:
```suggestion
      Collections.reverse(Arrays.asList(this.colors));
```

**Comment by bertek41** [comment]
Any eta for this?

**Review by kashike — APPROVED** [review]
