### PR TITLE
Lift "parent node is root" out of the while loop.

### LINKED ISSUE #165: Closing tags with no matching opening tag no longer show up in 4.2.0
[Originally a comment](https://github.com/KyoriPowered/adventure-text-minimessage/issues/135#issuecomment-895351121).

Technically a regression as from what I can tell, closing tags with no matching opening tags were preserved in 4.1.0

image
image

### PR DESCRIPTION
**Pull request by rymiel**
This way it also matches if the loop never runs (already at root level).

Also adds a test for it. Tests for unmatched closing tags NOT at root level already existed

Fixes #165

### CODE REVIEW

File: src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java [hunk 1]
```diff
@@ -1539,4 +1539,13 @@ void testCaseInsensitive() {
     this.assertParsedEquals(expected1, input1);
     this.assertParsedEquals(expected2, input2);
   }
+
+  @Test
+  void testClosingTagAtRootLevel() {
```
Comment (kezz) [inline src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java:1544]: Can you drop a link to issue just above this?

**Review by kezz — APPROVED** [review]

**Review by zml2008 — APPROVED** [review]
