### PR TITLE
fix: Enforce lowercase template keys

### LINKED ISSUE #190: Template of Component
When deserializing a Component with a template, who's value is also a Component, the template never gets applied. The code just ignores the template. Here's an example
```java
        Component test = MiniMessage.miniMessage().deserialize("<Player>: Test!",
                TemplateResolver.templates(Template.template("Player", e.getPlayer().displayName())));
        Bukkit.broadcast(test);
```
This code outputs some text that looks like ",<Player> Test!", when it should be replaced.

To show that this only happens with component templates, if the template gets changed to `Template.template("Player","abc")`;, it works perfectly fine and the output looks like "abc: Test!"

### PR DESCRIPTION
**Pull request by kezz**
Closes #190

### CODE REVIEW

**Review by broccolai — APPROVED** [review]

**Review by zml2008 — APPROVED** [review]

File: src/main/java/net/kyori/adventure/text/minimessage/Template.java [hunk 1]
```diff
@@ -167,6 +167,9 @@
     private final String value;
 
     StringTemplate(final @NotNull String key, final @NotNull String value) {
+      if (!key.toLowerCase().equals(key))
```
Comment (zml2008) [inline src/main/java/net/kyori/adventure/text/minimessage/Template.java:170]: key.toLowerCase(Locale.ROOT)

File: src/main/java/net/kyori/adventure/text/minimessage/Template.java [hunk 2]
```diff
@@ -206,6 +209,9 @@ public final String toString() {
     private final @NotNull Component value;
 
     public ComponentTemplate(final @NotNull String key, final @NotNull Component value) {
+      if (!key.toLowerCase().equals(key))
```
Comment (zml2008) [inline src/main/java/net/kyori/adventure/text/minimessage/Template.java:212]: key.toLowerCase(Locale.ROOT)

**Review by zml2008 — DISMISSED** [review]
